### PR TITLE
Allow binary download location to be specified

### PR DESCRIPTION
**Pull request by joshwlewis**
This allows a test run, or an entire pipeline to specify which sprettur it wants to use, with a default fallback to production. This is useful for integration tests on new sprettur features/changes.

### CODE REVIEW

**Comment by joshwlewis** [comment]
[Allow sprettur location to be specified](https://trello.com/c/9iZrgNih/2092-allow-sprettur-location-to-be-specified)

**Comment by gudmundur** [comment]
Not that I expect conflicts, but should we maybe name this `HEROKU_SPRETTUR_URL`?

**Comment by gudmundur** [comment]
I'm assuming the thinking is that we have a test pipeline in our staging environment where we'll set this config var to point at the Sprettur staging app?

**Comment by gudmundur** [comment]
👍

**Pull request merged**
